# The URL from which the site will be served
baseurl = "https://brianchu.netlify.app"
# Language used
languageCode = "en-us"
# Website title
title = "Brian Chu's homepage"
# Theme used
theme = "astatine"

rssLimit = 10
paginate = 10

# Code highlighting
pygmentsCodefences = true
pygmentsStyle = "native"

# Configure permalinks style
[permalinks]
    post = "/:slug/"
    page = "/:slug/"

# Configure main navbar links. They can have a weight to select the order.
# This links to content within the content/post/ folder
[[menu.main]]
    name = "Posts"
    url = "/post/"
    weight = -150

# This links to the page about.md
[[menu.main]]
    name = "About"
    url = "/about/"
    weight = -110

# Site wide params and SEO
[params]
    # Site description. Individual pages can have descriptions too but if
    # missing it will fallback to that one.
    description = "Brian's homepage"
    # Author of the site
    authorName = "Brian Chu"
    # Main image for the author. This will be the default image for SEO.
    [params.imgname]
        name = "img/main.jpg"
        # Add an alt description for the image
        alt = "Profile picture"

    # Indicate if you host Katex yourself. Defaults to using the CDN KaTex.
    # hostedKaTex = false
    
    # Enable link to feed in footer
    blogrss = false


# Sitemap location (default is /sitemap.xml)
[sitemap]
  filename = "sitemap.xml"
